version: '3'
services:
  notebook:
    image: helionagamachi/qiskit
    ports:
      - 8888:8888
    volumes:
      - ./tutorial:/home/developer/app/tutorial
    entrypoint:
      - jupyter
      - notebook
      - --ip
      - 0.0.0.0
      - --no-browser
      - tutorial/index.ipynb
