version: '3'
services:
  notebook:
    image: helionagamachi/qiskit
    ports:
      - 8888:8888
    volumes:
      - ./tutorial:/home/developer/app/tutorial
    entrypoint:
      - jupyter
      - notebook
      - --ip
      - 0.0.0.0
      - --no-browser
      - tutorial/index.ipynb
  python:
    image: helionagamachi/qiskit
    volumes:
      - ./code:/home/developer/app
      - requirements:/usr/local/lib/python3.6/site-packages
    env_file: my.env
    command:
      - bash
volumes:
  requirements:
